### ISSUE TITLE
Remove empty groups

### ISSUE THREAD

**Issue by ZAlexanderV** [mschuchard/terraform-local-ansible-inv#2]
When creating an inventory, if the groups(instances_aws, instances_gcp, instances_azr, instances_vsp) are empty, they are added to the inventory. Is it possible to delete empty groups to keep inventory clean?

**Comment by mschuchard** [comment]
Issue had been reproduced and resolved in cea34f93297c6225f8e47f9bcfd2f79440f10141 (note this commit has not yet been pushed at time of writing).

This will be part of the next release 1.3.1 at an unknown date.
